<?php

namespace THL\OnCallBundle\Entity;

use Doctrine\ORM\EntityRepository;
use MyProject\Proxies\__CG__\stdClass;
use THL\OnCallBundle\Generator\ScheduleGenerator;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository
{


    public function findScheduleFor($startDate, $endDate)
    {
        return '[
    {"date":"2013-02-04", "assignee":"Cosmin I."},
    {"date":"2013-02-05", "assignee":"Robert S."},
    {"date":"2013-02-06", "assignee":"Alexandru V."},
    {"date":"2013-02-07", "assignee":"Stefan V."},
    {"date":"2013-02-08", "assignee":"Cosmin I."},

    {"date":"2013-02-11", "assignee":"Robert S."},
    {"date":"2013-02-12", "assignee":"Alexandru V."},
    {"date":"2013-02-13", "assignee":"Stefan V."},
    {"date":"2013-02-14", "assignee":"Cosmin I."},
    {"date":"2013-02-15", "assignee":"Robert S."},

    {"date":"2013-02-18", "assignee":"Alexandru V."},
    {"date":"2013-02-19", "assignee":"Stefan V."},
    {"date":"2013-02-20", "assignee":"Cosmin I."},
    {"date":"2013-02-21", "assignee":"Robert S."},
    {"date":"2013-02-22", "assignee":"Alexandru V."},

    {"date":"2013-02-25", "assignee":"Stefan V."},
    {"date":"2013-02-26", "assignee":"Cosmin I."},
    {"date":"2013-02-27", "assignee":"Robert S."},
    {"date":"2013-02-28", "assignee":"Alexandru V."},
    {"date":"2013-03-01", "assignee":"Stefan V."}
]';
    }

    /**
     * @param \DateTime $start
     * @param \DateTime $end
     * @return array
     */
    public function generateSchedule(\DateTime $start, \DateTime $end)
    {
        $actors = $this->getEntityManager()->getRepository('THLOnCallBundle:Actor')->findAll();
        $generator = new ScheduleGenerator($actors, $start, $end);
        $schedule = array();
        foreach ($generator as $date => $actor) {
            $actorObject = new \stdClass();
            $actorObject->date = $date;
            $actorObject->assignee = (string)$actor;
            $schedule[] = $actorObject;
        }
        return json_encode($schedule, true);
    }
}
