parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: null
  database_name: oncall
  database_user: oncall
  database_password: oncall
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 7f44578d7f10104429be2d69c108f934710f
  database_path: null
