parameters:
  database_driver: pdo_mysql
  database_host: 192.168.12.73
  database_port: null
  database_name: cosmin
  database_user: cosmin
  database_password: parolacosmin
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 83d9d3c5ee351eab953a83ca6469657142ff37fe

